const global = {
  ratings: {
    '1': require('~/Assets/Images/recipePictures/1.png'),
    '2': require('~/Assets/Images/recipePictures/2.png'),
    '3': require('~/Assets/Images/recipePictures/3.png'),
    '4': require('~/Assets/Images/recipePictures/4.png'),
    '5': require('~/Assets/Images/recipePictures/5.png'),
    '6': require('~/Assets/Images/recipePictures/6.png'),
    '7': require('~/Assets/Images/recipePictures/7.png'),
    '8': require('~/Assets/Images/recipePictures/8.png'),
    '9': require('~/Assets/Images/recipePictures/9.png'),
    '10': require('~/Assets/Images/recipePictures/10.png'),
    '11': require('~/Assets/Images/recipePictures/11.png'),
    '12': require('~/Assets/Images/recipePictures/12.png'),
    '13': require('~/Assets/Images/recipePictures/13.png'),
    '14': require('~/Assets/Images/recipePictures/14.png'),
    '15': require('~/Assets/Images/recipePictures/15.png'),
    '16': require('~/Assets/Images/recipePictures/16.png'),
    '17': require('~/Assets/Images/recipePictures/17.png'),
    '18': require('~/Assets/Images/recipePictures/18.png'),
    '19': require('~/Assets/Images/recipePictures/19.png'),
    '20': require('~/Assets/Images/recipePictures/20.png'),
    '21': require('~/Assets/Images/recipePictures/21.png'),
    '22': require('~/Assets/Images/recipePictures/22.png'),
    '23': require('~/Assets/Images/recipePictures/23.png'),
    '24': require('~/Assets/Images/recipePictures/24.png'),
    '25': require('~/Assets/Images/recipePictures/25.png'),
    '26': require('~/Assets/Images/recipePictures/26.png'),
    '27': require('~/Assets/Images/recipePictures/27.png'),
    '28': require('~/Assets/Images/recipePictures/28.png'),
    '29': require('~/Assets/Images/recipePictures/29.png'),
    '30': require('~/Assets/Images/recipePictures/30.png'),
  },
};

export default global;
